src/main/java/com/kusitms/jipbap/auth/AuthController.java

chore: signup, signin 주소 변경

---

src/main/java/com/kusitms/jipbap/store/StoreService.java

fix: 이미지가 Null이 아닌경우만 업로드 할 수 있도록 변경

---

src/main/java/com/kusitms/jipbap/auth/AuthController.java
src/main/java/com/kusitms/jipbap/auth/AuthService.java
src/main/java/com/kusitms/jipbap/auth/dto/SignUpRequestDto.java
src/main/java/com/kusitms/jipbap/auth/dto/SignUpResponseDto.java

회원가입 할 때, userId 반환하도록 api 내용 수정

fix: 회원가입시 아이디 반환으로 api 변경

---

src/main/java/com/kusitms/jipbap/food/FoodController.java
src/main/java/com/kusitms/jipbap/food/FoodService.java
src/main/java/com/kusitms/jipbap/food/dto/HomeResponseDto.java
src/main/java/com/kusitms/jipbap/order/OrderRepository.java

feat: 홈 화면 api에 사용자 지역정보, 최근 주문된 음식, 별점 추가 api 기능 구현

---

src/main/java/com/kusitms/jipbap/auth/dto/SignInRequestDto.java
src/main/java/com/kusitms/jipbap/food/FoodController.java
src/main/java/com/kusitms/jipbap/food/FoodService.java
src/main/java/com/kusitms/jipbap/food/dto/FoodPreviewResponse.java
src/main/java/com/kusitms/jipbap/food/dto/HomeResponseDto.java

foodPreviewDto로 홈이랑 카테고리 하나로 통일
foodPreviewDto: 음식이미지, 가게이미지, 가게 Id 추가

feat: 음식 미리보기 dto 하나로 통일하고 데이터추가

---

src/main/java/com/kusitms/jipbap/common/response/ErrorCode.java
src/main/java/com/kusitms/jipbap/user/UserAddressExceptionController.java
src/main/java/com/kusitms/jipbap/user/UserAddressService.java
src/main/java/com/kusitms/jipbap/user/exception/PostalCodeNotFoundException.java

우편번호 값이 Null로 전달되는 오류에 대한 예외처리

feat: 유효하지 않은 우편번호 에러 추가

---

src/main/java/com/kusitms/jipbap/store/Store.java
src/main/java/com/kusitms/jipbap/store/StoreController.java
src/main/java/com/kusitms/jipbap/store/StoreService.java
src/main/java/com/kusitms/jipbap/store/dto/RegisterStoreRequestDto.java
src/main/java/com/kusitms/jipbap/store/dto/RegisterStoreResponse.java
src/main/java/com/kusitms/jipbap/user/UserAddressController.java

feat: 가게 등록 api 필드 추가

---

src/main/java/com/kusitms/jipbap/food/Food.java
src/main/java/com/kusitms/jipbap/food/FoodController.java
src/main/java/com/kusitms/jipbap/food/FoodService.java
src/main/java/com/kusitms/jipbap/food/dto/RegisterFoodRequestDto.java

메뉴 등록 시 상품 정보설명(이미지), 구성 성분(텍스트) 추가로 변경

feat: 메뉴 등록 api 필드 추가

---

src/main/java/com/kusitms/jipbap/order/dto/OrderPreviewResponse.java

fix: 주문 확인에서 배달/포장여부 추가

---

src/main/java/com/kusitms/jipbap/order/OrderController.java
src/main/java/com/kusitms/jipbap/order/OrderService.java
src/main/java/com/kusitms/jipbap/order/dto/ProcessingFoodDetailResponse.java
src/main/java/com/kusitms/jipbap/order/dto/ProcessingFoodResponse.java
src/main/java/com/kusitms/jipbap/order/dto/StoreProcessingResponse.java

feat: 가게마다 메뉴별 주문 확인 api 기능 구현

---

src/main/java/com/kusitms/jipbap/chat/domain/dto/MessageRequestDto.java
src/main/java/com/kusitms/jipbap/chat/domain/dto/RoomDto.java
src/main/java/com/kusitms/jipbap/chat/service/RoomService.java

feat: 채팅 수정

---

src/main/generated/com/kusitms/jipbap/order/QOrder.java
src/main/generated/com/kusitms/jipbap/order/QOrderDetail.java
src/main/java/com/kusitms/jipbap/chat/service/RoomService.java

fix: sendername이 null로 가는 문제 해결

---

src/main/java/com/kusitms/jipbap/food/FoodService.java

fix: 상품 등록시 상품정보 이미지 저장 안되는 문제 해결

---

src/main/java/com/kusitms/jipbap/chat/domain/dto/MessageDto.java
src/main/java/com/kusitms/jipbap/chat/domain/dto/MessageResponseDto.java
src/main/java/com/kusitms/jipbap/chat/domain/entity/Message.java
src/main/java/com/kusitms/jipbap/chat/repository/MessageRepository.java
src/main/java/com/kusitms/jipbap/chat/service/MessageService.java
src/main/java/com/kusitms/jipbap/chat/service/RoomService.java

issue #6 
채팅 관련 수정
메세지 전송시각 서버에서 계산 등

채팅 기능 업데이트

---

src/main/java/com/kusitms/jipbap/store/StoreService.java
src/main/java/com/kusitms/jipbap/store/dto/StoreFoodResponseDto.java

Related to: Issue #15
Issue #15

fix: 음식 검색시 응답형식 수정

---

src/main/java/com/kusitms/jipbap/order/OrderService.java

feat: fcm 메시지 전송

---

src/main/generated/com/kusitms/jipbap/notification/QNotification.java
src/main/java/com/kusitms/jipbap/auth/AuthController.java
src/main/java/com/kusitms/jipbap/auth/AuthService.java
src/main/java/com/kusitms/jipbap/user/UserController.java
src/main/java/com/kusitms/jipbap/user/UserService.java

issue #1 
refreshtoken 발급 로직 수정

refreshtoken 발급 로직 수정

---

src/main/java/com/kusitms/jipbap/auth/AuthController.java
src/main/java/com/kusitms/jipbap/auth/AuthService.java
src/main/java/com/kusitms/jipbap/config/SpringSecurityConfig.java
src/main/java/com/kusitms/jipbap/user/UserController.java
src/main/java/com/kusitms/jipbap/user/UserService.java

닉네임 관련 api 추가, 변경

---

src/main/java/com/kusitms/jipbap/food/Food.java
src/main/java/com/kusitms/jipbap/food/FoodOption.java
src/main/java/com/kusitms/jipbap/food/FoodService.java
src/main/java/com/kusitms/jipbap/food/dto/BestSellingFoodResponse.java
src/main/java/com/kusitms/jipbap/food/dto/FoodDetailByStoreResponse.java
src/main/java/com/kusitms/jipbap/food/dto/FoodDetailResponse.java
src/main/java/com/kusitms/jipbap/food/dto/FoodDto.java
src/main/java/com/kusitms/jipbap/food/dto/FoodOptionRequest.java
src/main/java/com/kusitms/jipbap/food/dto/FoodOptionResponse.java
src/main/java/com/kusitms/jipbap/food/dto/FoodPreviewResponse.java
src/main/java/com/kusitms/jipbap/food/dto/RegisterFoodRequestDto.java
src/main/java/com/kusitms/jipbap/order/Order.java
src/main/java/com/kusitms/jipbap/order/OrderDetail.java
src/main/java/com/kusitms/jipbap/order/OrderService.java
src/main/java/com/kusitms/jipbap/order/dto/OrderDto.java
src/main/java/com/kusitms/jipbap/order/dto/OrderFoodDetailRequest.java
src/main/java/com/kusitms/jipbap/order/dto/OrderFoodDetailResponse.java
src/main/java/com/kusitms/jipbap/order/dto/OrderFoodRequest.java
src/main/java/com/kusitms/jipbap/order/dto/OrderFoodResponse.java
src/main/java/com/kusitms/jipbap/order/dto/OrderHistoryResponse.java
src/main/java/com/kusitms/jipbap/store/Store.java
src/main/java/com/kusitms/jipbap/store/StoreService.java
src/main/java/com/kusitms/jipbap/store/dto/RegisterStoreRequestDto.java
src/main/java/com/kusitms/jipbap/store/dto/StoreDto.java
src/main/java/com/kusitms/jipbap/store/dto/StoreInfoDto.java

fix: 가격 데이터타입을 double로 변경

---

src/main/java/com/kusitms/jipbap/food/FoodService.java
src/main/java/com/kusitms/jipbap/store/Store.java
src/main/java/com/kusitms/jipbap/store/StoreService.java
src/main/java/com/kusitms/jipbap/store/dto/StoreInfoDto.java

feat: 가게 평점 double 타입으로 변경
